[".config/nvim"]
type = "archive"
url = "https://github.com/LazyVim/starter/archive/refs/heads/main.tar.gz"
exact = true
stripComponents = 1
refreshPeriod = "168h"
exclude = ["**/options.lua", "LICENSE", "README.md", ".github", ".gitignore"]
